### ISSUE TITLE
developもproductionも1つのplaybookで対応したい

### ISSUE THREAD

**Issue by shihou-ono** [apc-nw-auto-cft/auto_check_config_project#13]
前提の構想として、  
- inventoryにdevelopとproductionの2つのgroupを用意
- github actionsではworkflowを2つ用意
- 片方のworkflowはdevelopにmergeされたときに発動し、検証環境で検証を行う
  - extra_varsで`"{'is_develop':False}"`のような変数を渡す
- もう片方のworkflowはmainにmergeされたときに発動し、本番環境にconfigを投入する
  - extra_varsで`"{'is_develop':True}"`のような変数を渡す

extra_varsによって、inventoryのgroupのどちらを選ぶかを制御する

**Comment by uchida0411** [comment]
ご連絡いただきありがとうございます。
「Connectivity_check」および「config change」について、
集約・起動ブランチによる分岐ができましたのでクローズします。
