### ISSUE TITLE
k_uchida.txt 修正案

### ISSUE THREAD

**Issue by shihou-ono** [apc-nw-auto-cft/auto_check_config_project#14]
- https://github.com/apc-nw-auto-cft/auto_check_config_project/blob/1a11f8c0de0f8cdb45bf393f391ab099537b7bf2/presentation/k_uchida.txt#L60  
時間があれば、ここはもう少し詳しく説明して欲しいです。  
.github/workflow/github-actions-demo.yml を作成して、コピペして、git pushするだけでできちゃうというのは、github利用しててgithub actionsを利用していない人にはインパクトでかいと思います。
- https://github.com/apc-nw-auto-cft/auto_check_config_project/blob/1a11f8c0de0f8cdb45bf393f391ab099537b7bf2/presentation/k_uchida.txt#L72  
実行環境とはimageであるということと、imageを使うことで都度installする必要がないということをお伝えすると、ansibleで最近eeを使う流れなことの理解が深まりそうです。
- https://github.com/apc-nw-auto-cft/auto_check_config_project/blob/1a11f8c0de0f8cdb45bf393f391ab099537b7bf2/presentation/k_uchida.txt#L109  
ここの説明難しいですね。リモートからローカル => githubのリポジトリからgithub actionsで呼び出した実行環境  
と言い換えるとピンときやすいかも。
- https://github.com/apc-nw-auto-cft/auto_check_config_project/blob/1a11f8c0de0f8cdb45bf393f391ab099537b7bf2/presentation/k_uchida.txt#L137  
今回の利用方法ではuniqueである必要がありますね。けど、そこまでの詳細には触れなくても良いような。
- https://github.com/apc-nw-auto-cft/auto_check_config_project/blob/1a11f8c0de0f8cdb45bf393f391ab099537b7bf2/presentation/k_uchida.txt#L157  
https://github.com/apc-nw-auto-cft/auto_check_config_project/blob/1a11f8c0de0f8cdb45bf393f391ab099537b7bf2/presentation/k_uchida.txt#L161  
これは誤解がありそうですね。  
include_varsというmoduleはfileに書かれている内容をそのまま変数として読み込みます（もちろん、yamlかjson形式にしておく必要あり）。 
で、NW機器相手だと想像しにくいかもですが、対象inventoryがSVだったり何かしらのhostだとすると、delegate_to: localhostを付けないと、その機器の中に入ってるfileを変数として読み込もうとするんですね。  
けど、今回はvarsのfileがlocalhostにあるからdelegate_to: localhostとしている、ということです。

**Comment by uchida0411** [comment]
ご連絡いただきありがとうございます。
7/27の発表が無事完了しましたのでクローズします。
