### ISSUE TITLE
k_kitamura.txt 修正案

### ISSUE THREAD

**Issue by shihou-ono** [apc-nw-auto-cft/auto_check_config_project#15]
https://github.com/apc-nw-auto-cft/auto_check_config_project/blob/1a11f8c0de0f8cdb45bf393f391ab099537b7bf2/presentation/k_kitamura.txt#L30
https://github.com/apc-nw-auto-cft/auto_check_config_project/blob/1a11f8c0de0f8cdb45bf393f391ab099537b7bf2/presentation/k_kitamura.txt#L31

ここはもう少し丁寧に説明しましょうか。  
VMX01からVMX02へのloopback, VMX02からVMX01へのloopbackそれぞれへの経路で、metricが1のge0/0/0を経由していることがわかります。  
その後ospfの設定で双方のge-0/0/0.0 の metric を 150に変更したので、metricが3のge0/0/2が最適経路として選択されたことがわかります。  
みたいな感じで。

**Comment by uchida0411** [comment]
ご連絡いただきありがとうございます。
7/27の発表が無事完了しましたのでクローズします。
