### ISSUE TITLE
Change from "git add ." to "git add project/backup/."

### ISSUE THREAD

**Issue by shihou-ono** [apc-nw-auto-cft/auto_check_config_project#57]
https://github.com/apc-nw-auto-cft/auto_check_config_project/blob/54f0c44a93fe9aca3b7f610e5e7500b790d9b02d/.github/workflows/GA_commit_and_inspect.yaml#L108

ここを  
`git add project/backup/.`
にすると、このworkflowで変更が生じうるファイルに限定できて良いように思いました。

**Comment by uchida0411** [comment]
ご連絡いただきありがとうございます。
ご指摘の通りでしたので修正を行いました。

具体的な動作テストは行えてませんが、
pwdを追加してprojectの1階層上にいることを確認できましたので、
記法・動作として問題ないと判断します。
