### ISSUE TITLE
Use var for inventory file to decrease steps

### ISSUE THREAD

**Issue by shihou-ono** [apc-nw-auto-cft/auto_check_config_project#58]
https://github.com/apc-nw-auto-cft/auto_check_config_project/blob/54f0c44a93fe9aca3b7f610e5e7500b790d9b02d/.github/workflows/GA_commit_and_inspect.yaml#L66

ここでは、inventory fileの指定をするために `if` を使ってます。  
これを、`github.ref` からvarにできるようになると、分岐せずに書けてstepを削減できそう、というIdeaです。

まず、inventoryを例えば  
project/inventory/develop/inventory.yaml  
project/inventory/production/inventory.yaml  
に格納しておきます。

`github.ref` を 何らかの方法で`/` でsplitしてarrayにできればとても簡単で、  
`project/inventory/{{ github.ref.split("/")[2] }}/inventory.yaml`  
みたくできるかと思います。が、そんな方法があるかは分かってないです。

これならきっといけるというのは、
```
env:
  dev_or_prod: ${{ endsWith(github.ref, "develop") && "develop" || endsWith(github.ref, "production") && "production" }}
```  
というように定義しておいて、  
`project/inventory/{{ dev_or_prod }}/inventory.yaml`  
とする方法です。  
これは、  
https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions  
を参考に書いてみました。

**Comment by uchida0411** [comment]
ご連絡いただきありがとうございます。
「Connectivity_check」および「config change」について、
集約・起動ブランチによる分岐ができましたのでクローズします。

    env:
　　dev_or_prod: ${{ endswith(github.ref, 'develop') && 'develop' || endsWith(github.ref, 'main') && 'production' }}
のうえで
　　ansible-playbook -i project/inventory/${dev_or_prod}/inventory.yaml \
といった感じの書き方
